name: Continuous Integration
description: "Cache and install npm dependencies"
runs:
  using: composite
  steps:
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      run: npm ci
