name: Install npm dependencies and Node.js
description: Install and cache npm dependencies and Node.js
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      shell: bash
      run: |
        npm ci
